kind: Service
apiVersion: v1
metadata:
  namespace: ci
  labels:
    app: jenkins
    stack: ci
  name: jenkins-svc
spec:
  type: LoadBalancer
  selector:
    app: jenkins 
  ports:
  - name: http
    port: 8080
    protocol: TCP
